fos_http_cache:
    # https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/tags.html
    tags:
        enabled: true

    # https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/proxy-client.html
    proxy_client:
        varnish:
            tag_mode: purgekeys
            http:
                servers:
                    - '%env(PURGE_SERVER)%'
                #base_url: yourwebsite.com

    # https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/headers.html
    cache_control:
        defaults:
            overwrite: true
        rules:
            # We could set cache headers in config if we did not have access to edit controller.
            #
            # Example here is using reverse_proxy_ttl here to avoid other proxies caching the page:
            # https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/headers.html#reverse-proxy-ttl
            # This is useful if you are caching content for logged in users..

            # match post action of BlogController
            -
                match: { path: .*/blog/posts/.* }
                headers:
                    cache_control: { public: true, s_maxage: 0 }
                    reverse_proxy_ttl: 3000

            # match index action of BlogController
            -
                match: { path: .*/blog/$ }
                headers:
                    cache_control: { public: true, s_maxage: 0 }
                    reverse_proxy_ttl: 3000

    # https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/user-context.html
    user_context:
        enabled: true
        hash_cache_ttl: 900
        # By default we enable role_provider so user context hash varies by symfony role which is everything we need on demo here.
        # Custom providers is also possible in case of more advance roles logic or other factors that should be part of hash:
        # https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/user-context.html#custom-context-providers
        role_provider: true
        # By default FOS Http cache has this enabled. As we want to opt in, we disable and add headers in controller
        always_vary_on_context_hash: false
